### ISSUE TITLE
PHP notice in select sanitization

### ISSUE THREAD

**Issue by ernilambar** [WPTRT/code-examples#1]
I am using function `theme_slug_sanitize_select` for sanitizing select control. But PHP notice is returned as below.
`Notice: Trying to get property of non-object on ....`

I checked `setting->id` and it is returning correct value. I guess PHP notice is due to `$setting->manager`. What may be problem here?

**Comment by chipbennett** [comment]
Note: these code examples are not intended to be drop-in ready. They are merely examples for how to implement the code. Whether or not, and how, they work really depends on the specific implementation. Thus, it really isn't feasible to provide support for that specific implementation.

That said, in regard to your specific question, the most likely culprit is your setting `ID` and control `ID` not being the same value.
