### ISSUE TITLE
Setting defaults

### ISSUE THREAD

**Issue by gsarig** [WPTRT/code-examples#11]
Hello,

from what I have read so far, the appropriate way to call a customizer setting is by declaring its default value, for example: 

``` php
get_theme_mod('my_setting', 'default_value');
```

When you have to call the setting in many different places, though, it might be problematic if you decide to change your default value. What I was thinking of doing was a function where I would set the customizer default values only once. For example, something like that:

``` php
if( ! function_exists('my_default') ) :
function my_default( $key = '' ) {
    $def = array(
        'setting1' => 'default_value',
        'setting2' => 'default_value'
    );
    if( isset($def[$key]) ) {
        return $def[$key];
    }
}
endif;
```

Then, in the customizer settings, instead of setting the default like this:

``` php
'default'  => 'my_default_value',
```

I would do it like this:

``` php
'default'  => my_default('setting1'),
```

and I would call the value in the templates like that:

``` php
get_theme_mod('my_setting', my_default('setting1'));
```

That way I would only need to declare my defaults in one place. Would this approach comply with WordPress' good practices or is there any other, preferred way for dealing with the issue?

**Comment by grappler** [comment]
Yes, this looks good. This is was @chipbennett wrote in his post on WordPress.org https://make.wordpress.org/themes/2014/07/09/using-sane-defaults-in-themes/

**Comment by gsarig** [comment]
Thanks for the response. I did search for a more "official" solution but I couldn't find Chip's post. 

Anyway, I did a small correction to my code, to prevent a warning if the user calls the function without passing a parameter.

**Comment by ernilambar** [comment]
As this is a general question, not issue specific to the repo, I am closing ticket.
