### ISSUE TITLE
How to embed these settings ?

### ISSUE THREAD

**Issue by wpthemes786** [WPTRT/code-examples#3]
Hello. 
I want to know that how to embed these customizer settings? Should i include these into themes.

Thanks

**Comment by chipbennett** [comment]
Please refer to this post:
https://make.wordpress.org/themes/2015/05/07/customizer-tutorials-and-documentation/

These are code examples intended to help teach how to implement the Customizer API, and are not intended to be drop-in ready to any particular Theme.
